# Arabic for every English string on the Packages and Thank-you pages. Keys are the exact English text.
# build_pkgs.py stops with an error if a string is missing here, so add the Arabic whenever you add English.
AR = {
# ---- countries
"United States": "الولايات المتحدة",
"United Kingdom": "المملكة المتحدة",
"Canada": "كندا",
"Estonia": "إستونيا",
"Poland": "بولندا",
"France": "فرنسا",
"UAE": "الإمارات",
"Saudi Arabia": "السعودية",
"Oman": "سلطنة عُمان",
"Malaysia": "ماليزيا",
"Thailand": "تايلاند",
"Pakistan": "باكستان",
"LLC in Wyoming or New Mexico (Delaware on request). Owned 100% by non-residents.": "شركة ذات مسؤولية محدودة (LLC) في وايومنغ أو نيومكسيكو (وديلاوير عند الطلب)، مملوكة بالكامل لغير المقيمين.",
"Private limited company (Ltd) at Companies House. No UK-resident director needed.": "شركة خاصة محدودة (Ltd) مسجّلة في Companies House، دون الحاجة إلى مدير مقيم في بريطانيا.",
"Ontario or BC corporation. No resident-director rule in either province.": "شركة في أونتاريو أو كولومبيا البريطانية، ولا يشترط أيٌّ من الإقليمين وجود مدير مقيم.",
"Private limited company (OÜ), run fully online with e-Residency.": "شركة خاصة محدودة (OÜ) تُدار بالكامل عبر الإنترنت باستخدام الإقامة الإلكترونية.",
"Limited liability company (sp. z o.o.) via the S24 online system.": "شركة ذات مسؤولية محدودة (sp. z o.o.) عبر نظام S24 الإلكتروني.",
"Simplified joint-stock company (SAS/SASU). Minimum capital €1.": "شركة مساهمة مبسّطة (SAS/SASU) بحد أدنى لرأس المال 1 يورو.",
"Free zone company (fastest) or mainland LLC (trade anywhere in the UAE).": "شركة في منطقة حرة (الأسرع)، أو شركة ذات مسؤولية محدودة في البر الرئيسي (للتجارة في أي مكان داخل الإمارات).",
"LLC with an investment licence (MISA) for foreign owners.": "شركة ذات مسؤولية محدودة بترخيص استثماري من وزارة الاستثمار (MISA) للملاك الأجانب.",
"LLC with 100% foreign ownership for most activities.": "شركة ذات مسؤولية محدودة بملكية أجنبية كاملة لمعظم الأنشطة.",
"Private limited company (Sdn. Bhd.) at SSM. Our home base.": "شركة خاصة محدودة (Sdn. Bhd.) مسجّلة لدى SSM. هنا مقرّنا الرئيسي.",
"Thai limited company. Foreign ownership limits apply to many activities.": "شركة تايلاندية محدودة. تنطبق قيود على ملكية الأجانب في كثير من الأنشطة.",
"Private limited company at SECP.": "شركة خاصة محدودة مسجّلة لدى هيئة الأوراق المالية (SECP).",
# ---- tier names
"Starter": "الأساسية",
"Business": "الأعمال",
"Complete": "الشاملة",
"Standard": "القياسية",
"Full setup": "الإعداد الكامل",
"Free zone, no visa": "منطقة حرة بدون تأشيرة",
"Free zone + 1 visa": "منطقة حرة + تأشيرة واحدة",
"Mainland LLC": "شركة في البر الرئيسي",
"Market-entry assessment": "تقييم دخول السوق",
"Company setup": "تأسيس الشركة",
"Setup + investor visa": "التأسيس + تأشيرة مستثمر",
"Setup + compliance": "التأسيس + الامتثال",
"Work permit": "تصريح العمل",
# ---- "plus" lines
"Everything in Starter, plus": "كل ما في الأساسية، بالإضافة إلى",
"Everything in Business, plus": "كل ما في الأعمال، بالإضافة إلى",
"Everything in Standard, plus": "كل ما في القياسية، بالإضافة إلى",
"Everything in no-visa, plus": "كل ما في باقة بدون تأشيرة، بالإضافة إلى",
"Everything in setup, plus": "كل ما في التأسيس، بالإضافة إلى",
# ---- US
"State filing fee included": "رسوم التسجيل في الولاية مشمولة",
"Articles of organization & operating agreement": "عقد التأسيس واتفاقية التشغيل",
"EIN application for non-residents": "طلب الرقم الضريبي (EIN) لغير المقيمين",
"Registered agent, 12 months": "وكيل مسجّل لمدة 12 شهراً",
"Digital document pack": "ملف المستندات الرقمية",
"US business mailing address, 12 months": "عنوان بريدي تجاري في أمريكا لمدة 12 شهراً",
"Business account application support (one provider)": "دعم طلب حساب تجاري (مزوّد واحد)",
"Amazon / Shopify readiness call": "مكالمة تجهيز للبيع على أمازون / شوبيفاي",
"First-year Form 5472 + pro-forma 1120 filing": "تقديم نموذج 5472 ونموذج 1120 الشكلي للسنة الأولى",
"State annual report filing": "تقديم التقرير السنوي للولاية",
"Compliance calendar & reminders": "تقويم الالتزامات وتذكيرات بالمواعيد",
"Delaware: add $100. Delaware charges a $400 yearly tax from 2026.": "ديلاوير: أضف $100. تفرض ديلاوير ضريبة سنوية قدرها $400 ابتداءً من 2026.",
"Yearly renewal from $499 (registered agent + annual report).": "التجديد السنوي يبدأ من $499 (الوكيل المسجّل + التقرير السنوي).",
# ---- UK
"Companies House fee (£100) included": "رسوم Companies House (100 جنيه إسترليني) مشمولة",
"Director identity verification": "التحقق من هوية المدير",
"Registered office address, 12 months": "عنوان مكتب مسجّل لمدة 12 شهراً",
"Share certificates & digital documents": "شهادات الأسهم والمستندات الرقمية",
"Director service address, 12 months": "عنوان خدمة للمدير لمدة 12 شهراً",
"HMRC Corporation Tax (UTR) registration": "التسجيل في ضريبة الشركات لدى HMRC (رقم UTR)",
"Business account application support": "دعم طلب الحساب التجاري",
"VAT registration if needed": "التسجيل في ضريبة القيمة المضافة عند الحاجة",
"First-year accounts via our accountant partner": "حسابات السنة الأولى عبر المحاسب الشريك لنا",
"Confirmation statement filing (£50 fee included)": "تقديم بيان التأكيد السنوي (رسوم 50 جنيهاً إسترلينياً مشمولة)",
"Yearly renewal from $449 (registered office + confirmation statement).": "التجديد السنوي يبدأ من $449 (المكتب المسجّل + بيان التأكيد).",
# ---- CA
"Government fees & NUANS name search included": "الرسوم الحكومية والبحث عن الاسم عبر NUANS مشمولة",
"Articles & bylaws": "عقد التأسيس واللوائح الداخلية",
"Business Number (BN) registration": "التسجيل للحصول على رقم الأعمال (BN)",
"Digital minute book": "سجل المحاضر الرقمي",
"GST/HST registration": "التسجيل في ضريبة GST/HST",
"Amazon.ca readiness call": "مكالمة تجهيز للبيع على Amazon.ca",
"Federal corporation available on request (25% of directors must be Canadian residents).": "الشركة الفيدرالية متاحة عند الطلب (يجب أن يكون 25% من المديرين مقيمين في كندا).",
# ---- EE
"State fee (€265) included": "الرسوم الحكومية (265 يورو) مشمولة",
"Articles of association": "النظام الأساسي للشركة",
"Legal address & contact person, 12 months": "عنوان قانوني وشخص اتصال لمدة 12 شهراً",
"Registration guidance for e-Residency holders": "إرشاد التسجيل لحاملي الإقامة الإلكترونية",
"Business account (EMI) application support": "دعم طلب حساب تجاري لدى مؤسسة نقود إلكترونية (EMI)",
"Accounting partner introduction": "تعريفك بمحاسب شريك",
"You apply for e-Residency yourself and pay its fee to the Estonian government. e-Residency is not a visa or residence permit.": "تتقدّم بطلب الإقامة الإلكترونية بنفسك وتدفع رسومها للحكومة الإستونية. الإقامة الإلكترونية ليست تأشيرة ولا تصريح إقامة.",
# ---- PL
"Court & publication fees included": "رسوم المحكمة والنشر مشمولة",
"KRS registration via S24": "التسجيل في السجل الوطني (KRS) عبر S24",
"Tax ID & VAT registration": "الرقم الضريبي والتسجيل في ضريبة القيمة المضافة",
"Virtual office, 12 months": "مكتب افتراضي لمدة 12 شهراً",
"Qualified e-signature setup": "إعداد التوقيع الإلكتروني المعتمد",
"Sworn translations": "ترجمات محلّفة",
"Business bank account support": "دعم فتح الحساب البنكي التجاري",
"Minimum share capital of PLN 5,000 is paid into your company and stays your money; it isn't included in the price.": "الحد الأدنى لرأس المال 5,000 زلوتي يُودَع في حساب شركتك ويبقى مالك، وهو غير مشمول في السعر.",
"Accounting is mandatory in Poland and quoted separately.": "المحاسبة إلزامية في بولندا ويُقدَّم لها عرض سعر منفصل.",
# ---- FR
"Articles (statuts) drafted": "صياغة النظام الأساسي (statuts)",
"Legal notice publication included": "نشر الإعلان القانوني مشمول",
"Guichet unique filing & registration": "التقديم والتسجيل عبر البوابة الموحّدة (Guichet unique)",
"Registered address (domiciliation), 12 months": "عنوان مسجّل (domiciliation) لمدة 12 شهراً",
"Capital deposit & bank account support": "إيداع رأس المال ودعم فتح الحساب البنكي",
"EU VAT number registration": "التسجيل للحصول على رقم ضريبة القيمة المضافة الأوروبي",
"Cdiscount / Octopia seller readiness": "التجهيز للبيع على Cdiscount / Octopia",
"A non-EU manager may need a French residence permit to run day-to-day operations in France.": "قد يحتاج المدير من خارج الاتحاد الأوروبي إلى تصريح إقامة فرنسي لإدارة العمل اليومي في فرنسا.",
# ---- AE
"Licence in a cost-effective free zone": "رخصة في منطقة حرة مناسبة التكلفة",
"Company documents & registration": "مستندات الشركة والتسجيل",
"Bank account application support": "دعم طلب الحساب البنكي",
"One investor/employee visa": "تأشيرة واحدة لمستثمر أو موظف",
"Emirates ID & medical coordination": "تنسيق الهوية الإماراتية والفحص الطبي",
"Corporate tax registration": "التسجيل في ضريبة الشركات",
"Licence, office and approvals": "الرخصة والمكتب والموافقات",
"Quoted after a short call": "عرض السعر بعد مكالمة قصيرة",
"Pay a deposit of $500 online. It's credited to your package; the final price depends on the free zone and activity.": "ادفع عربوناً قدره $500 عبر الإنترنت، ويُخصم من قيمة باقتك. السعر النهائي يعتمد على المنطقة الحرة ونوع النشاط.",
"Licences renew yearly at roughly the first-year cost.": "تُجدَّد الرخص سنوياً بتكلفة قريبة من تكلفة السنة الأولى.",
# ---- SA
"Activity & licence route review": "مراجعة النشاط ومسار الترخيص",
"Capital and Saudization overview": "نظرة عامة على رأس المال ونسب السعودة",
"Written plan and quote": "خطة مكتوبة وعرض سعر",
"Credited if you go ahead": "يُخصم المبلغ إذا قررت المتابعة",
"Investment licence & commercial registration": "الترخيص الاستثماري والسجل التجاري",
"Chamber & municipality registrations": "التسجيل في الغرفة التجارية والبلدية",
"Bank account support": "دعم فتح الحساب البنكي",
"Government fees and capital not included": "الرسوم الحكومية ورأس المال غير مشمولة",
"Setup usually takes 3–6 weeks. Work permits and expat levies are separate.": "يستغرق التأسيس عادةً من 3 إلى 6 أسابيع. تصاريح العمل والمقابل المالي للعمالة الوافدة منفصلة.",
# ---- OM
"Commercial registration": "السجل التجاري",
"Activity licences": "تراخيص النشاط",
"Company documents": "مستندات الشركة",
"Chamber of commerce registration": "التسجيل في غرفة التجارة والصناعة",
"One investor residence visa": "تأشيرة إقامة مستثمر واحدة",
"Office space, when your activity requires it, is quoted separately.": "المكتب، إن تطلّبه نشاطك، له عرض سعر منفصل.",
# ---- MY
"SSM incorporation fee included": "رسوم التأسيس لدى SSM مشمولة",
"Company secretary, 12 months": "سكرتير الشركة لمدة 12 شهراً",
"Registered address, 12 months": "عنوان مسجّل لمدة 12 شهراً",
"Constitution & company documents": "دستور الشركة ومستنداتها",
"Shopee / Lazada / TikTok Shop setup call": "مكالمة إعداد للبيع على شوبي / لازادا / تيك توك شوب",
"SST & licence check": "مراجعة ضريبة المبيعات والخدمات (SST) والتراخيص",
"A foreign-owned Sdn Bhd needs at least one director resident in Malaysia. If you don't have one, we quote a resident director service separately.": "تحتاج الشركة المملوكة لأجانب إلى مدير واحد على الأقل مقيم في ماليزيا. إن لم يكن لديك، نقدّم عرض سعر منفصلاً لخدمة المدير المقيم.",
"Audit and tax filing are yearly obligations, quoted separately.": "التدقيق والإقرار الضريبي التزامات سنوية لها عرض سعر منفصل.",
# ---- TH
"Ownership & activity review": "مراجعة الملكية والنشاط",
"Government registration fees included": "رسوم التسجيل الحكومية مشمولة",
"Company documents & tax ID": "مستندات الشركة والرقم الضريبي",
"VAT registration": "التسجيل في ضريبة القيمة المضافة",
"Accounting partner setup": "الترتيب مع محاسب شريك",
"Per person": "للشخص الواحد",
"Eligibility check first": "التحقق من الأهلية أولاً",
"Application & visa coordination": "تقديم الطلب وتنسيق التأشيرة",
"Each foreign work permit generally needs THB 2M paid-up capital and 4 Thai employees (BOI companies differ). The Thai authorities decide.": "يتطلّب كل تصريح عمل لأجنبي عادةً رأس مال مدفوعاً قدره 2 مليون بات و4 موظفين تايلانديين (تختلف شركات BOI). القرار للجهات التايلاندية المختصة.",
"BOI promotion and Foreign Business Licence are quoted separately.": "امتيازات BOI ورخصة الأعمال الأجنبية لها عرض سعر منفصل.",
# ---- PK
"Name reservation & incorporation": "حجز الاسم والتأسيس",
"Tax number (NTN) registration": "التسجيل للحصول على الرقم الضريبي (NTN)",
"Security clearance filing for foreign shareholders": "تقديم طلب التصريح الأمني للمساهمين الأجانب",
"Chamber registration": "التسجيل في الغرفة التجارية",
"Foreign directors and shareholders need security clearance, which can take 8–14 weeks.": "يحتاج المديرون والمساهمون الأجانب إلى تصريح أمني قد يستغرق من 8 إلى 14 أسبوعاً.",
# ---- add-ons
"Amazon seller account application support": "دعم طلب حساب بائع على أمازون",
"Marketplace onboarding: Noon, TikTok Shop, Shopee and others": "التسجيل في المنصات: نون وتيك توك شوب وشوبي وغيرها",
"Shopify store setup": "إعداد متجر شوبيفاي",
"Business bank or payment account application (per provider)": "طلب حساب بنكي تجاري أو حساب دفع (لكل مزوّد)",
"Amazon FBA prep from Malaysia": "تجهيز شحنات أمازون FBA من ماليزيا",
"Document attestation / apostille": "تصديق المستندات / الأبوستيل",
"$299": "$299",
"$249 each": "$249 لكل منصة",
"from $490": "من $490",
"$199": "$199",
"quote": "حسب الطلب",
# ---- packages page
"Packages": "الباقات",
"Clear prices for forming your company abroad": "أسعار واضحة لتأسيس شركتك في الخارج",
"Pick a country and a package. Prices show in your local currency, and you pay exactly the price you see. They include government filing fees unless a note says otherwise. Not sure which fits? Book a free consultation first.": "اختر الدولة والباقة. تظهر الأسعار بعملتك المحلية، وتدفع المبلغ الظاهر نفسه تماماً. تشمل الأسعار الرسوم الحكومية للتسجيل ما لم تذكر الملاحظة غير ذلك. لست متأكداً من الأنسب لك؟ احجز استشارة مجانية أولاً.",
"Prices in": "الأسعار بعملة",
"Quote": "حسب الطلب",
"from": "يبدأ من",
"Most popular": "الأكثر طلباً",
"Buy now": "اشترِ الآن",
"Pay": "ادفع",
"deposit": "عربوناً",
"Get a quote": "اطلب عرض سعر",
"Add-ons": "إضافات",
"Add to any package": "أضِفها إلى أي باقة",
"Bank, payment and marketplace accounts are approved by each provider. Our add-ons cover preparing and submitting a complete application.": "قبول الحسابات البنكية وحسابات الدفع والمنصات يعود لكل مزوّد. إضافاتنا تغطي تجهيز طلب مكتمل وتقديمه.",
"After you pay": "بعد الدفع",
"What happens next": "ماذا يحدث بعد ذلك",
"Secure payment": "دفع آمن",
"You pay by card on a secure checkout page run by our payment provider.": "تدفع بالبطاقة عبر صفحة دفع آمنة يديرها مزوّد الدفع لدينا.",
"Onboarding form": "نموذج البيانات",
"You send your details and documents so we can check eligibility.": "ترسل بياناتك ومستنداتك لنتحقق من الأهلية.",
"Review": "المراجعة",
"We confirm everything with you before anything is filed.": "نؤكّد معك كل التفاصيل قبل تقديم أي شيء.",
"Filing": "التقديم",
"We register the company and send your documents as each step completes.": "نسجّل الشركة ونرسل إليك المستندات مع اكتمال كل خطوة.",
"Handover": "التسليم",
"You receive your company documents and next-step checklist.": "تستلم مستندات شركتك وقائمة بالخطوات التالية.",
'By paying you agree to our <a href="terms.html">Terms of Service</a> and <a href="refund.html">Refund Policy</a>. If we find your case can\'t go ahead, you get a refund under the Refund Policy.': 'بإتمام الدفع فإنك توافق على <a href="terms.html">شروط الخدمة</a> و<a href="refund.html">سياسة الاسترداد</a>. إذا تبيّن لنا أن حالتك لا يمكن المضي فيها، تسترد المبلغ وفق سياسة الاسترداد.',
# ---- thank-you page
"Payment": "الدفع",
"Thank you": "شكراً لك",
"We're confirming your payment.": "نتحقق الآن من دفعتك.",
"Checking your payment…": "جارٍ التحقق من الدفع…",
"Onboarding details": "بيانات التسجيل",
"We use these details to check eligibility and prepare your filings. We'll ask for passport copies separately over a secure channel.": "نستخدم هذه البيانات للتحقق من الأهلية وتجهيز طلبات التسجيل. سنطلب نسخ جوازات السفر لاحقاً عبر قناة آمنة.",
"Full name (as on passport)": "الاسم الكامل (كما في جواز السفر)",
"Email": "البريد الإلكتروني",
"WhatsApp number": "رقم واتساب",
"Nationality": "الجنسية",
"Full residential address": "عنوان السكن الكامل",
"National ID number": "رقم الهوية الوطنية",
"Passport number": "رقم جواز السفر",
"Proposed company names (up to 3, in order of preference)": "أسماء الشركة المقترحة (حتى 3 أسماء، حسب الأفضلية)",
"Business activity": "نشاط الشركة",
"e.g. selling skincare products on Amazon US": "مثال: بيع منتجات العناية بالبشرة على أمازون أمريكا",
"Owners": "الملاك",
"Single owner": "مالك واحد",
"Two or more partners": "شريكان أو أكثر",
"If selling online": "في حال البيع أونلاين",
"Not applicable": "لا ينطبق",
"My own private brand": "علامتي التجارية الخاصة",
"Reselling other brands": "إعادة بيع علامات أخرى",
"Anything else we should know?": "هل هناك ما يجب أن نعرفه؟",
'I confirm these details are correct and I agree to the <a href="terms.html">Terms of Service</a> and <a href="privacy.html">Privacy Policy</a>.': 'أؤكد أن هذه البيانات صحيحة، وأوافق على <a href="terms.html">شروط الخدمة</a> و<a href="privacy.html">سياسة الخصوصية</a>.',
'<span class="dot"></span>Send my details': '<span class="dot"></span>أرسل بياناتي',
"Details received": "تم استلام بياناتك",
"Thank you. We'll review your details and contact you on WhatsApp or email within one business day.": "شكراً لك. سنراجع بياناتك ونتواصل معك عبر واتساب أو البريد الإلكتروني خلال يوم عمل واحد.",
}
